### ISSUE TITLE
Program not cache messages, fix it

### ISSUE THREAD

**Issue by groschovskiy** [relatedcode/RealtimeChat#27]
Need create class for receive data from Firebase and store all message in local database. This is very primary task. For this option use CoreData, because this database use Whatsapp and Viber in own messengers.

**Comment by khalilleo** [comment]
https://www.firebase.com/docs/ios/guide/offline-capabilities.html

Firebase has offline capabilities which can save *ALL* chat history locally, check the link above.

BTW anyone knows how to make ChatView only display let's say 100 messages when view loads, but user can load more when scoll up?

**Comment by groschovskiy** [comment]
@khalilleo thanks for information
