### ISSUE TITLE
Twitter Login Failing

### ISSUE THREAD

**Issue by Xenero** [relatedcode/RealtimeChat#33]
I've gone into the AppDelegate.m file and modified the PFTwitterUtils line to reflect my own app details:

`[PFTwitterUtils initializeWithConsumerKey:@"CONSUMER_KEY_HERE" consumerSecret:@"CONSUMER_SECRET_HERE"];`

Now, when I try logging in using Twitter, the console shows the following error:

`2016-04-27 13:12:41.317 app[659:173001] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x181129900 0x180797f80 0x1810181a8 0x181018040 0x100208e50 0x10020ab8c 0x100735bf0 0x100735bb0 0x10073b658 0x1810e0bb0 0x1810dea18 0x18100d680 0x18251c088 0x185e84d90 0x1001a5c18 0x180bae8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

Any idea what is going on here?

**Comment by Xenero** [comment]
Any answer to this? I've payed for a product that doesn't seem to work as described.

**Comment by relatedcode** [comment]
@Xenero I have double checked. The Twitter login working fine. You need to configure your Twitter app in the right way.

**Comment by Xenero** [comment]
perhaps some instruction on "the right way" would be helpful. I've followed the instructions in your README.md file.

Simply closing it by saying it's working is not good enough.

**Comment by relatedcode** [comment]
@Xenero Just drop me a mail to discuss the details.
