### ISSUE TITLE
firebase rules

### ISSUE THREAD

**Issue by BhavinBhadani** [relatedcode/RealtimeChat#35]
what is firebase rules structure??? If I put my Firebase URL, it doesn't work. So it might be problem with security rules and can you please share your firebase structure ... thanx!!!!

**Comment by canaksoy** [comment]
for indexing:

```
{
    "rules": {
        ".read": true,
        ".write": true,
        "Recent": {
          ".indexOn": ["userId", "groupId"]
        }
    }
}
```
