### ISSUE TITLE
Premium Version Pop Up

### ISSUE THREAD

**Issue by gurtajs4** [relatedcode/RealtimeChat#39]
Hi,

Keep Up for nice work,very nicely written app code. I am always getting a popup saying to use premium version. Do I have to buy premium version to use this app, or is there a way to disable this?

Thanks
Gurtaj

**Comment by relatedcode** [comment]
@gurtajs4 To remove popup ad, you need to buy the Premium version.

**Comment by gurtajs4** [comment]
What are the features difference between demo and paid version?

Thanks
Gurtaj

**Comment by relatedcode** [comment]
@gurtajs4 The popup will be removed. :)

**Comment by happy2share** [comment]
Does anybody found solution to this issue?

**Comment by relatedcode** [comment]
@happy2share You need to buy the Premium version to remove the popup ad.

**Comment by gurtajs4** [comment]
I have a it working with POP Removed. It was a hell lot of reverse engineering :)
