### ISSUE TITLE
In-App Video / Voice Chat

### ISSUE THREAD

**Issue by tommiris** [relatedcode/RealtimeChat#48]
Hi, not an issue but just want to seek clarification on the app.

I am actually quite interested in buying your premium version for the In-App video/voice features. May I ask what framework do you use for those features? Do you use companies like Twilio or Nexmo for those features (Ie. there will be ongoing costs involved)? 

Thanks!

**Comment by relatedcode** [comment]
You can check the 3rd party frameworks in the Installation section:

https://github.com/relatedcode/RealtimeChat#installation

All frameworks have separated pricing. You check the details on their website.
