### ISSUE TITLE
How would you add picture messaging? Would you solely use Firebase?

### ISSUE THREAD

**Issue by ryderjack** [relatedcode/RealtimeChat#5]
Hi,

Awesome library here btw. 

Basically I'm trying to add picture messaging support and have seen this is supported by the JSQMessagesController. Would you be able to point me in the right direction RE once i have a UIImage how would i then send this to firebase?

Thanks,

Jack

**Comment by relatedcode** [comment]
As far as I know Firebase is a text only backend. If you need picture messaging support in RaltimeChat, you should save the picture at Parse and load from Parse when necessary.

**Comment by ryderjack** [comment]
thanks for the speedy response! Also i noticed JSQMessages supports footer labels to the cells. If i wanted to implement 'seen' labels does Firebase support this kind of thing?

Cheers

**Comment by relatedcode** [comment]
Yes, I think that could be done by Firebase.
