### ISSUE TITLE
VoiP with close app

### ISSUE THREAD

**Issue by oskarko** [relatedcode/RealtimeChat#51]
HI, mate!

great app, great example! thank you for all your time and knowledge shared here with all of us ;)

little question, when I make a call (or video call) just receive the push but not the call with closed app like Skype does, how can I implement this feature?

**Comment by Tysoftwares** [comment]
Please what kind of software application can I use to compile this source code in Windows

**Comment by relatedcode** [comment]
@oskarko Thanks for the feedback. The VoIP related update is in progress.

**Comment by relatedcode** [comment]
The Sinch SDK has been update to the latest version. Please check now. Thanks!
